#!/usr/bin/env tsx
// Planner adapter (local mode) - Stub implementation
// Reads objective from stdin, outputs task JSON

import * as readline from 'readline';

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
  terminal: false
});

let inputBuffer = '';

rl.on('line', (line) => {
  inputBuffer += line;
});

rl.on('close', () => {
  const objective = inputBuffer.trim();

  // Stub: Generate deterministic sample task
  const task = {
    task_id: `task-${Date.now()}`,
    role: 'builder',
    objective: objective || 'Build feature X',
    inputs: {
      files: ['backend/core/contacts/contact-service.ts'],
      acceptance: ['Feature works', 'Tests pass', '85%+ coverage']
    },
    constraints: {
      loc_max: 300,
      pack: 'crm_pack',
      branch: 'feature/planned'
    },
    status: 'open',
    notes: 'Generated by planner_local stub'
  };

  console.log(JSON.stringify(task, null, 2));
});
