#!/usr/bin/env tsx
// Planner adapter (HTTP mode) - Stub implementation
// Posts objective to HTTP endpoint, returns task JSON

interface PlannerRequest {
  objective: string;
}

interface PlannerResponse {
  task_id: string;
  role: string;
  objective: string;
  inputs: { files: string[]; acceptance: string[] };
  constraints: { loc_max: number; pack: string; branch?: string };
  status: string;
  notes?: string;
}

export async function planViaHttp(endpoint: string, objective: string): Promise<PlannerResponse> {
  // Stub: Simulate HTTP call with sample response
  console.error(`[HTTP] Planning via ${endpoint}`);

  return {
    task_id: `task-http-${Date.now()}`,
    role: 'builder',
    objective: objective || 'Build feature via HTTP',
    inputs: {
      files: ['backend/core/deals/deal-service.ts'],
      acceptance: ['Feature works', 'Tests pass']
    },
    constraints: {
      loc_max: 300,
      pack: 'crm_pack'
    },
    status: 'open',
    notes: 'Generated by planner_http stub'
  };
}

// CLI mode
if (require.main === module) {
  const objective = process.argv[2] || 'Default objective';
  const endpoint = process.env.PLANNER_ENDPOINT || 'http://localhost:3001/api/plan';

  planViaHttp(endpoint, objective).then(task => {
    console.log(JSON.stringify(task, null, 2));
  });
}
