#!/usr/bin/env tsx
// Reviewer adapter (local mode) - Stub implementation
// Reads PR URL from stdin, outputs rubric JSON

import * as readline from 'readline';

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
  terminal: false
});

let inputBuffer = '';

rl.on('line', (line) => {
  inputBuffer += line;
});

rl.on('close', () => {
  const startTime = Date.now();
  const prUrl = inputBuffer.trim();

  // Stub: Generate deterministic rubric review (aligned with review.schema.json)
  const review = {
    pr_url: prUrl || 'https://github.com/org/repo/pull/123',
    scores: {
      correctness: 5,
      type_safety: 5,
      security: 4,
      observability: 4,
      dx_ergonomics: 5,
      test_coverage: 4,
      incrementality: 5,
      risk_control: 4
    },
    evidence: [
      { file: 'example.ts', line: 42, note: 'Zero any types' },
      { file: 'example.ts', line: 89, note: 'Explicit return types' }
    ],
    total: 36,
    percentage: 90,
    verdict: 'approve',
    required_changes: [],
    optional_suggestions: ['Consider adding JSDoc'],
    notes: 'Generated by reviewer_local stub'
  };

  // Output review + metrics
  const latencyMs = Date.now() - startTime;
  console.log(JSON.stringify(review, null, 2));
  console.error(JSON.stringify({ helper: 'reviewer', mode: 'local', latency_ms: latencyMs, success: true }));
});
