#!/usr/bin/env tsx
// Reviewer adapter (HTTP mode) - Stub implementation
// Posts PR URL to HTTP endpoint, returns rubric JSON

interface ReviewerRequest {
  pr_url: string;
}

interface ReviewerResponse {
  pr_url: string;
  scores: Record<string, number>;
  total: number;
  percentage: number;
  verdict: string;
  required_changes: string[];
  optional_suggestions: string[];
  notes?: string;
}

export async function reviewViaHttp(endpoint: string, prUrl: string): Promise<ReviewerResponse> {
  // Stub: Simulate HTTP call with sample response
  console.error(`[HTTP] Reviewing via ${endpoint}`);

  return {
    pr_url: prUrl,
    scores: {
      correctness: 5,
      type_safety: 5,
      security: 4,
      observability: 4,
      dx_ergonomics: 5,
      test_coverage: 4,
      incrementality: 5,
      risk_control: 4
    },
    total: 36,
    percentage: 90,
    verdict: 'approve',
    required_changes: [],
    optional_suggestions: ['Consider adding structured logs'],
    notes: 'Generated by reviewer_http stub'
  };
}

// CLI mode
if (require.main === module) {
  const prUrl = process.argv[2] || 'https://github.com/org/repo/pull/1';
  const endpoint = process.env.REVIEWER_ENDPOINT || 'http://localhost:3002/api/review';

  reviewViaHttp(endpoint, prUrl).then(review => {
    console.log(JSON.stringify(review, null, 2));
  });
}
