# Elaria ClientForge - Full Security & Quality Audit
# Runs: Security Scan → Dependency Audit → Code Quality Check

Write-Host ""
Write-Host "🔍 ============================================" -ForegroundColor Cyan
Write-Host "   CLIENTFORGE FULL SECURITY AUDIT" -ForegroundColor Cyan
Write-Host "============================================" -ForegroundColor Cyan
Write-Host ""

Set-Location "D:\clientforge-crm"

# Stage 1: MCP Security Scan
Write-Host "[1/4] Security Vulnerability Scan..." -ForegroundColor Yellow
Write-Host "→ Scanning for SQL injection, XSS, secrets..." -ForegroundColor Gray

# Check if LM Studio API is available
$lmstudioAvailable = $false
try {
    Invoke-RestMethod -Uri "http://localhost:1234/v1/models" -Method Get -ErrorAction Stop | Out-Null
    $lmstudioAvailable = $true
} catch {
    Write-Host "⚠️  LM Studio not running - skipping MCP security scan" -ForegroundColor Yellow
}

if ($lmstudioAvailable) {
    $body = @{
        model = "qwen2.5-30b"
        messages = @(
            @{
                role = "user"
                content = "Scan workspace for security vulnerabilities and provide a summary report"
            }
        )
        stream = $false
    } | ConvertTo-Json -Depth 10

    try {
        $result = Invoke-RestMethod -Uri "http://localhost:1234/v1/chat/completions" -Method Post -Body $body -ContentType "application/json"
        Write-Host "✓ Security scan complete" -ForegroundColor Green
        Write-Host ""
        Write-Host "Security Report:" -ForegroundColor Yellow
        Write-Host $result.choices[0].message.content
        Write-Host ""
    } catch {
        Write-Host "⚠️  Security scan failed: $_" -ForegroundColor Yellow
    }
} else {
    Write-Host "✓ Skipped (LM Studio not available)" -ForegroundColor Yellow
}
Write-Host ""

# Stage 2: npm audit
Write-Host "[2/4] Dependency Vulnerability Audit..." -ForegroundColor Yellow
npm audit --json | Out-File "D:\clientforge-crm\06_BACKUPS\audits\npm-audit-$(Get-Date -Format 'yyyy-MM-dd').json"
npm audit
Write-Host "✓ Dependency audit complete" -ForegroundColor Green
Write-Host ""

# Stage 3: Outdated packages
Write-Host "[3/4] Checking for Outdated Packages..." -ForegroundColor Yellow
npm outdated
Write-Host "✓ Package check complete" -ForegroundColor Green
Write-Host ""

# Stage 4: Code quality metrics
Write-Host "[4/4] Code Quality Metrics..." -ForegroundColor Yellow

# Count files
$tsFiles = (Get-ChildItem -Path "D:\clientforge-crm" -Recurse -Include *.ts,*.tsx -Exclude node_modules | Measure-Object).Count
$jsFiles = (Get-ChildItem -Path "D:\clientforge-crm" -Recurse -Include *.js,*.jsx -Exclude node_modules | Measure-Object).Count
$totalFiles = $tsFiles + $jsFiles

# Count lines of code
$totalLines = 0
Get-ChildItem -Path "D:\clientforge-crm" -Recurse -Include *.ts,*.tsx,*.js,*.jsx -Exclude node_modules | ForEach-Object {
    $totalLines += (Get-Content $_.FullName | Measure-Object -Line).Lines
}

Write-Host "  → Total Files: $totalFiles" -ForegroundColor Gray
Write-Host "  → TypeScript: $tsFiles" -ForegroundColor Gray
Write-Host "  → JavaScript: $jsFiles" -ForegroundColor Gray
Write-Host "  → Total Lines: $totalLines" -ForegroundColor Gray
Write-Host "✓ Metrics collected" -ForegroundColor Green

# Generate audit report
$timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
$reportPath = "D:\clientforge-crm\06_BACKUPS\audits\audit-report-$(Get-Date -Format 'yyyy-MM-dd_HHmmss').md"

$report = @"
# ClientForge Security & Quality Audit Report

**Date**: $timestamp
**Generated By**: Elaria Command Center

---

## 📊 Code Metrics

- **Total Files**: $totalFiles
- **TypeScript Files**: $tsFiles
- **JavaScript Files**: $jsFiles
- **Total Lines of Code**: $totalLines

---

## 🔒 Security Scan

$(if ($lmstudioAvailable) { "✓ Completed via MCP security server" } else { "⚠️  Skipped (LM Studio not running)" })

---

## 📦 Dependency Audit

$(npm audit --json | ConvertFrom-Json | ForEach-Object {
    $_.metadata | Format-List | Out-String
})

---

## 📝 Recommendations

1. Review npm audit output for critical vulnerabilities
2. Update outdated packages with security patches
3. Address any security scan findings
4. Run full test suite before deployment

---

**Report Location**: $reportPath
"@

New-Item -ItemType Directory -Path "D:\clientforge-crm\06_BACKUPS\audits" -Force | Out-Null
$report | Out-File $reportPath -Encoding UTF8

# Summary
Write-Host ""
Write-Host "============================================" -ForegroundColor Cyan
Write-Host "✅ AUDIT COMPLETE!" -ForegroundColor Green
Write-Host "============================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "Audit Results:" -ForegroundColor Yellow
Write-Host "  ✓ Security Scan: $(if ($lmstudioAvailable) { 'Complete' } else { 'Skipped' })" -ForegroundColor $(if ($lmstudioAvailable) { 'Green' } else { 'Yellow' })
Write-Host "  ✓ Dependency Audit: Complete" -ForegroundColor Green
Write-Host "  ✓ Package Check: Complete" -ForegroundColor Green
Write-Host "  ✓ Code Metrics: Complete" -ForegroundColor Green
Write-Host ""
Write-Host "📄 Full report: $reportPath" -ForegroundColor Cyan
Write-Host ""

# Ask to open report
$openReport = Read-Host "Open audit report? (Y/N)"
if ($openReport -eq "Y" -or $openReport -eq "y") {
    Start-Process notepad.exe $reportPath
}
